### ISSUE TITLE
Scoreboard are getting null and not being send to the client

### ISSUE THREAD

**Issue by TheWylot** [NEZNAMY/VelocityScoreboardAPI#2]
```
  Status:
    Title: TextHolderImpl{legacyText=§cQuake, modernText=TextComponentImpl{content="", style=StyleImpl{obfuscated=not_set, bold=not_set, strikethrough=not_set, underlined=not_set, italic=not_set, color=null, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[TextComponentImpl{content="Quake", style=StyleImpl{obfuscated=false, bold=false, strikethrough=false, underlined=false, italic=false, color=NamedTextColor{name="red", value="#ff5555"}, clickEvent=null, hoverEvent=null, insertion=null, font=null}, children=[]}]}, holder=com.velocitypowered.proxy.protocol.packet.chat.ComponentHolder@7a552ab2}
    HealthDisplay: integer
    NumberFormat: null
    DisplaySlot: SIDEBAR
    Scores (9):
      §8§r:
        Score: 9
        DisplayName: null
        NumberFormat: null
      §4§r:
        Score: 5
        DisplayName: null
        NumberFormat: null
      §5§r:
        Score: 6
        DisplayName: null
        NumberFormat: null
      §6§r:
        Score: 7
        DisplayName: null
        NumberFormat: null
      §7§r:
        Score: 8
        DisplayName: null
        NumberFormat: null
      §0§r:
        Score: 1
        DisplayName: null
        NumberFormat: null
      §1§r:
        Score: 2
        DisplayName: null
        NumberFormat: null
      §2§r:
        Score: 3
        DisplayName: null
        NumberFormat: null
      §3§r:
        Score: 4
        DisplayName: null
        NumberFormat: null
        
        
  ```
  
  
  i should relogin to the server to randomly get this fixed. trying to reproduce is just use an Internal Plugin that has scoreboard (bedwars plugins or stuff like that) then disable TAB scoreboard on that world/server.
